app/modules/users/parent/models.py
from flask import Flask 
from modules.users.models import User

class Parent(User):
    def signup(self, data) :
        parent = User().signup(data)
        return parent

 

app/modules/users/parent/routes.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, session
import pymongo
from modules.users.parent.models import Parent
from bson.objectid import ObjectId

# Create a blueprint named 'parent_bp'
parent_bp = Blueprint('parent_bp', __name__)

# MongoDB connection
client = pymongo.MongoClient("mongodb+srv://Osnat:123456!@cluster1.7pvmkvu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1")
db = client.get_database("total_records")

@parent_bp.route("/homepage", methods=['GET'])
def Parent_Index():
    return render_template("parent/indexParent.html")

@parent_bp.route('/profile', methods=['GET', 'POST'])
def profile_parent_form():
    if request.method == 'POST':
        old_email = session.get('email')
        updated_email = request.form.get("email")  # Get the new email from the form
        updated_data = {
            "name": request.form.get("name"),
            "email": updated_email,
            "phone": request.form.get("phone"),
            "password": request.form.get("password")
        }
        
        # Update the parent's data
        db.parents.update_one({"email": old_email}, {"$set": updated_data})
        
        # Update the parent_email in the students collection
        db.students.update_many({"parent_email": old_email}, {"$set": {"parent_email": updated_email}})
        
        # Update the email in the session
        session['email'] = updated_email

        return render_template("parent/indexParent.html", user=updated_data)
    
    else:
        email = session.get('email')
        user_data = db.parents.find_one({"email": email})
        if user_data:
            return render_template("parent/ParentProfile.html", user=user_data)
        else:
            return "User not found"




# @parent_bp.route('/profile', methods=['GET', 'POST'])
# def profile_parent_form():
#     if request.method == 'POST':
#         email = session.get('email')
#         updated_data = {
#             "name": request.form.get("name"),
#             "email": request.form.get("email"),
#             "phone": request.form.get("phone"),
#             "password": request.form.get("password")
#         }
#         db.parents.update_one({"email": email}, {"$set": updated_data})
#         return render_template("parent/indexParent.html", user=updated_data)
#     else:
#         email = session.get('email')
#         user_data = db.parents.find_one({"email": email})
#         if user_data:
#             return render_template("parent/ParentProfile.html", user=user_data)
#         else:
#             return "User not found"

@parent_bp.route("/MyStudent", methods=['GET'])
def MyStudent_form():
    # session['origin'] = 'MyStudentList'
    email = session.get('email')
    parent = db.parents.find_one({"email": email})
    if parent:
        students1 = []
        for student_email in parent.get('students', []):
            student = db.students.find_one({"email": student_email})
            if student:
                students1.append(student)

        return render_template("parent/MyStudentList.html", students=students1)
    else:
        return "Parent not found"
    

@parent_bp.route("/editstudentquestionnaire", methods=['GET'])
def edit_student_questionnaire():
    email = request.args.get('email')
    parent_email = request.args.get('parent_email')
    
    # Use the email to fetch the questionnaire data
    questionnaire_data = db.questionnaire.find_one({"student_email": email})
    
    if questionnaire_data:
        return render_template('parent/EditStudentQuestionnaire.html', questionnaire=questionnaire_data)
    else:
        return "Questionnaire not found"


@parent_bp.route("/updatestudentquestionnaire", methods=['POST'])
def update_studentb_questionnaire():
    form_data = request.form.to_dict()
    email = form_data.get('email')  # Use the hidden field from the form

    questionnaire_data = {
        "student_email": form_data.get('email'),
        "parent_email": form_data.get('parent_email'),
        "full_name": form_data.get('fullName'),
        "grade": form_data.get('grade'),
        "rating": form_data.get('rating'),
        "first_subject": form_data.get('firstSubject'),
        "second_subject": form_data.get('secondSubject'),
    }

    db.questionnaire.update_one({"student_email": email}, {"$set": questionnaire_data})
    return render_template('parent/indexParent.html')

@parent_bp.route("/Tips", methods=['GET'])
def Tips_page():
    return render_template("parent/Tips.html")


@parent_bp.route("/payment/<lesson_id>", methods=['GET'])
def payment_page(lesson_id):
    parent_email = session.get('email')
    if not parent_email:
        return redirect(url_for('login'))

    lesson = db.private_lesson.find_one({'_id': ObjectId(lesson_id), 'parent_email': parent_email})
    if not lesson:
        return redirect(url_for('parent_bp.lessons_payments_page'))

    return render_template("parent/payment.html", lesson=lesson)

@parent_bp.route('/lessons_payments')
def lessons_payments_page():
    parent_email = session.get('email')
    if not parent_email:
        return redirect(url_for('login'))

    lessons = db.private_lesson.find({'parent_email': parent_email})
    lessons_list = []
    for lesson in lessons:
        if lesson.get('date') and lesson.get('paid') == False:
            student = db.students.find_one({'email': lesson['student_email']})
            lesson['student_name'] = student['name'] if student else lesson['student_email']
            lessons_list.append(lesson)

    return render_template('parent/lessons_payments.html', lessons=lessons_list)

@parent_bp.route("/process_payment/<lesson_id>", methods=['POST'])
def process_payment(lesson_id):
    parent_email = session.get('email')
    if not parent_email:
        return redirect(url_for('login'))

    lesson = db.private_lesson.find_one({'_id': ObjectId(lesson_id), 'parent_email': parent_email})
    if not lesson:
        return redirect(url_for('parent_bp.lessons_payments_page'))

    db.private_lesson.update_one({'_id': ObjectId(lesson_id)}, {'$set': {'paid': True}})
    return redirect(url_for('parent_bp.Parent_Index'))




@parent_bp.route('/select_child_uploadQ', methods=['GET'])
def select_child_uploadQ():
    parent_email = session.get('email')
    parent = db.parents.find_one({'email': parent_email})
    children = parent.get('students', [])
    return render_template('parent/select_child_uploadQ.html', children=children)


@parent_bp.route("/uplod_question", methods=['GET'])
def upload_question():
    child_email = request.args.get('child_email')
    session['child_email'] = child_email  

    if not child_email:
        return redirect(url_for('parent_bp.select_child'))
    return render_template('parent/upload_question.html', child_email=child_email)
   

@parent_bp.route('/save_question', methods=['POST'])
def save_question():
    question = request.form.get('question')
    possible_answers = request.form.getlist('possible_answers[]')
    correct_answer = request.form.get('correct_answer')
    explanation = request.form.get('explanation')
    child_email = session.get('child_email')
    
    # Save to the database
    db.parentQuestion.insert_one({
        'child_email': child_email,
        'question': question,
        'possible_answers': possible_answers,
        'correct_answer': correct_answer,
        'explanation': explanation
    })

    action = request.form.get('action')
    
    if action == 'insert_another':
        return render_template('parent/upload_question.html', child_email=child_email)
    else:
        return redirect(url_for('parent_bp.some_confirmation_page'))



@parent_bp.route('/some_confirmation_page', methods=['GET'])
def some_confirmation_page():
    return render_template('parent/confirmation.html')

@parent_bp.route('/select_child', methods=['GET'])
def select_child():
    parent_email = session.get('email')
    parent = db.parents.find_one({'email': parent_email})
    children = parent.get('students', [])
    return render_template('parent/select_child.html', children=children)


@parent_bp.route("/progress", methods=['GET'])
def progress():
    student_email = request.args.get('student_email')
    return render_template('parent/progress.html', student_email=student_email)


@parent_bp.route('/show_progress', methods=['GET'])
def show_progress():
    child_email = request.args.get('child_email')
    if not child_email:
        return redirect(url_for('parent_bp.select_child'))

    # Fetch child's progress from both collections
    child_procss_data = db.childProcess.find_one({'student_email': child_email})
    tests_eval_data = db.testsEval.find_one({'student_email': child_email})

    if not child_procss_data and not tests_eval_data:
            return render_template('parent/progress.html', progress_data={}, child_email=child_email)

        
    if not child_procss_data:
        progress_data = {
            'tests_eval': tests_eval_data.get('answers', [])
        }

    elif not tests_eval_data:
        progress_data = {
            'child_procss': child_procss_data.get('answers', []),
    }
          
    else:
        # Combine and process data as needed for display
        progress_data = {
            'child_procss': child_procss_data.get('answers', []),
            'tests_eval': tests_eval_data.get('answers', [])
        }

    return render_template('parent/progress.html', progress_data=progress_data, child_email=child_email)

@parent_bp.route('/view_reports', methods=['GET'])
def view_reports():
    print("View reports route accessed.")  # Debugging line
    parent_email = session.get('email')
    if not parent_email:
        print("No email found in session.")  # Debugging line
        return render_template('parent/reports.html', error="No email found in session.")

    # Fetch the list of student emails from the parent table
    parent_record = db.parents.find_one({'email': parent_email})
    if not parent_record:

app/modules/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
import pymongo
from modules.users.student.models import Student
from modules.users.teacher.models import Teacher
from modules.users.parent.models import Parent
import modules.users.utils as utils

# Create a blueprint named 'users_bp'
users_bp_main = Blueprint('users_bp_main', __name__)

client = pymongo.MongoClient("mongodb+srv://Osnat:123456!@cluster1.7pvmkvu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1")
db = client.get_database("total_records")


@users_bp_main.route("/home", methods=['GET'])
def Home():
    return render_template("index.html")

@users_bp_main.route("/signup", methods=['GET'])
def signup_form():
    return render_template("signupPage.html")


# @users_bp_main.route('/student_questionnaire', methods=['GET', 'POST'])
# def view_student_questionnaire():
#     email = request.args.get('email')
#     origin = session.get('origin') 
#     student = db.students.find_one({"email": email})

#     if origin == 'MyStudentList':
#         email = request.args.get('email')
#         if request.method == 'POST':
#             updated_questionnaire_data = {
#                 "student_email": request.form.get('email'),
#                 "parent_email": request.form.get('parent_email'),
#                 "full_name": request.form.get('fullName'),
#                 "grade": request.form.get('grade'),
#                 "rating": request.form.get('rating'),
#                 "first_subject": request.form.get('firstSubject'),
#                 "second_subject": request.form.get('secondSubject'),
#             }
#             db.questionnaire.update_one({"email": email}, {"$set": updated_questionnaire_data})
#             return redirect(url_for('parent/indexParent'))
#         else:
#             email = request.args.get('email')
#             questionnaire_data = db.questionnaire.find_one({"email": email})
#             if questionnaire_data:
#                 return render_template("student/questionnaire.html", student=questionnaire_data)
#     elif origin == 'signuppage':
#         return redirect(url_for('student.bp.questionnaire'))
#     else:
#         return "User not found"

#     return render_template('student/questionnaire.html', student=student)

@users_bp_main.route("/signup", methods=['POST'])
def signup():
    data = request.form.to_dict()
    email = data.get('email')

    if not utils.verify_name(data.get('name')):
        return render_template("signupPage.html", error="Name must contain only English letters.", form_data=data)

    # Validate phone number
    if not utils.verify_phone_number(data.get('phone')):
        return render_template("signupPage.html", error="Phone number must consist of exactly 10 digits.", form_data=data)

    # Validate password
    if not utils.verify_password(data.get('password')):
        return render_template("signupPage.html", error="Password must be at least 6 characters long and contain at least one letter and one digit.", form_data=data)

    if db.parents.find_one({"email": email}) or db.teachers.find_one({"email": email}) or db.students.find_one({"email": email}):
        return render_template("signupPage.html", error="Email already exists. Please use a different email.", form_data=data)

    if data.get('role') == 'Student':
        parent_email = data.get('parent_email')
        parent = db.parents.find_one({"email": parent_email, "role": "Parent"})
        if not parent:
            return render_template("signupPage.html", error="Parent email not found. Please provide a valid parent email.", form_data=data)

        db.parents.update_one({"email": parent_email}, {"$addToSet": {"students": data['email']}})
        data["parent_email"] = parent_email
        
        user = Student().signup(data)
        db.students.insert_one(user)
        session['origin'] = 'signuppage'
        return redirect(url_for('student_bp.questionnaire', email=data['email']))
    
    elif data.get('role') == 'Parent':
        user = Parent().signup(data)
        db.parents.insert_one(user)
    
    else:
        grade_range = data.get('grade_range')
        teacher_age = data.get('teacher_age')
        user = Teacher().signup(data)
        user["grade_range"] = grade_range
        user["teacher_age"] = teacher_age
        db.teachers.insert_one(user)
    
    return redirect(url_for('home'))


@users_bp_main.route("/login", methods=['GET'])
def login_form():
    return render_template("login.html")

@users_bp_main.route("/login", methods=['POST'])
def login():
    data = request.form
    email = data.get('email')
    password = data.get('password')

    parent = db.parents.find_one({"email": email, "password": password})
    if parent:
        session['email'] = email
        session['name'] = parent.get('name')  # Assuming 'name' is a field in the parents collection
        return render_template('parent/indexParent.html')

    teacher = db.teachers.find_one({"email": email, "password": password})
    if teacher:
        session['email'] = email
        session['name'] = teacher.get('name')  # Assuming 'name' is a field in the teachers collection
        return render_template('teacher/indexTeacher.html')

    student = db.students.find_one({"email": email, "password": password})
    if student:
        session['email'] = email
        session['name'] = student.get('name')  # Assuming 'name' is a field in the students collection
        return render_template('student/indexStudent.html')

    # If login fails, pass back the email and an error message
    return render_template("login.html", error="Invalid username or password.", email=email)

@users_bp_main.route("/FQA", methods=['GET'])
def FQA_page():
    return render_template("FQA.html")

app/templates/parent/select_child.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Select Child</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- CSS Libraries -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

     <!--Favicon -->
     <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">

     <!-- Google Web Fonts -->
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link
         href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap"
         rel="stylesheet">
 
     <!-- Icon Font Stylesheet -->
     <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
 
     <!-- Libraries Stylesheet -->
     <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
     <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
 
     <!-- Customized Bootstrap Stylesheet -->
     <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
 
     <!-- Template Stylesheet -->
     <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0">
            <a href="{{url_for('parent_bp.Parent_Index') }}" class="navbar-brand">
                <h1 class="m-0 text-primary"><i class="fa fa-book-reader me-3"></i>MathTake</h1>
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav mx-auto">
                    <a href="{{url_for('parent_bp.Parent_Index') }}" class="nav-item nav-link active">Home</a>
                    <a href="#about" class="nav-item nav-link">About Us</a>
                    <a href="{{ url_for('users_bp_main.FQA_page') }}" class="nav-item nav-link">FAQ</a>
                    <!-- Added FAQ link -->

                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu rounded-0 rounded-bottom border-0 shadow-sm m-0">
                            <a href="{{ url_for('parent_bp.Tips_page') }}" class="dropdown-item">Tips</a>
                            <a href="{{ url_for('parent_bp.lessons_payments_page') }}" class="dropdown-item">lessons
                                payments</a>
                            <a href="{{ url_for('parent_bp.select_child') }}" class="dropdown-item">Child Process</a>
                            <a href="{{ url_for('parent_bp.select_child_uploadQ') }}" class="dropdown-item">Upload
                                Question</a>
                            <a href="{{ url_for('parent_bp.view_reports') }}" class="dropdown-item">Reports</a>
                        </div>
                    </div>
                </div>
                <a href="{{ url_for('parent_bp.profile_parent_form') }}"
                    class="btn btn-primary rounded-pill px-3 d-none d-lg-block">Profile<i
                        class="fa fa-arrow-right ms-3"></i></a>
                <a href="{{ url_for('logout') }}" class="btn btn-primary rounded-pill px-3 d-none d-lg-block">logout<i
                        class="fa fa-arrow-right ms-3"></i></a>
            </div>
        </nav>
        <!-- Navbar End -->
        


        <!-- Page Header Start -->
        <div class="container-xxl py-5 page-header position-relative mb-5">
            <div class="container py-5">
                <h1 class="display-2 text-white animated slideInDown mb-4">Select Child</h1>
            </div>
        </div>
        <!-- Page Header End -->


        <div class="container">
            <form action="{{ url_for('parent_bp.show_progress') }}" method="GET">
                <div class="form-group">
                    <label for="child_email">Choose a child:</label>
                    <select class="form-control" name="child_email" id="child_email" required>
                        {% for child in children %}
                            <option value="{{ child }}">{{ child }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary w-100">View Progress</button>
            </form>
            
        </div>
    
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
    
        <!-- Template Javascript -->
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
        
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

app/templates/parent/select_child_uploadQ.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Select Child</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- CSS Libraries -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    <!--Favicon -->
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
         
        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0">
            <a href="{{url_for('parent_bp.Parent_Index') }}" class="navbar-brand">
                <h1 class="m-0 text-primary"><i class="fa fa-book-reader me-3"></i>MathTake</h1>
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav mx-auto">
                    <a href="{{url_for('parent_bp.Parent_Index') }}" class="nav-item nav-link active">Home</a>
                    <a href="#about" class="nav-item nav-link">About Us</a>
                    <a href="{{ url_for('users_bp_main.FQA_page') }}" class="nav-item nav-link">FAQ</a>
                    <!-- Added FAQ link -->

                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu rounded-0 rounded-bottom border-0 shadow-sm m-0">
                            <a href="{{ url_for('parent_bp.Tips_page') }}" class="dropdown-item">Tips</a>
                            <a href="{{ url_for('parent_bp.lessons_payments_page') }}" class="dropdown-item">lessons
                                payments</a>
                            <a href="{{ url_for('parent_bp.select_child') }}" class="dropdown-item">Child Process</a>
                            <a href="{{ url_for('parent_bp.select_child_uploadQ') }}" class="dropdown-item">Upload
                                Question</a>
                            <a href="{{ url_for('parent_bp.view_reports') }}" class="dropdown-item">Reports</a>
                        </div>
                    </div>
                </div>
                <a href="{{ url_for('parent_bp.profile_parent_form') }}"
                    class="btn btn-primary rounded-pill px-3 d-none d-lg-block">Profile<i
                        class="fa fa-arrow-right ms-3"></i></a>
                <a href="{{ url_for('logout') }}" class="btn btn-primary rounded-pill px-3 d-none d-lg-block">logout<i
                        class="fa fa-arrow-right ms-3"></i></a>
            </div>
        </nav>
        <!-- Navbar End -->
        


        <!-- Page Header Start -->
        <div class="container-xxl py-5 page-header position-relative mb-5">
            <div class="container py-5">
                <h1 class="display-2 text-white animated slideInDown mb-4">Select Child</h1>
            </div>
        </div>
        <!-- Page Header End -->


        <div class="container">
            <form action="{{ url_for('parent_bp.upload_question') }}" method="GET">
                <div class="form-group">
                    <select name="child_email" id="child_email" class="form-control" required>
                        {% for child in children %}
                            <option value="{{ child }}">{{ child }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top: 10px;">Upload Questions</button>
            </form>
            
        </div>
    
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
        <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
    
        <!-- Template Javascript -->
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
        
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>