app/modules/users/parent/routes.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, session
import pymongo
from modules.users.parent.models import Parent
from bson.objectid import ObjectId

# Create a blueprint named 'parent_bp'
parent_bp = Blueprint('parent_bp', __name__)

# MongoDB connection
client = pymongo.MongoClient("mongodb+srv://Osnat:123456!@cluster1.7pvmkvu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1")
db = client.get_database("total_records")

@parent_bp.route("/homepage", methods=['GET'])
def Parent_Index():
    return render_template("parent/indexParent.html")

@parent_bp.route('/profile', methods=['GET', 'POST'])
def profile_parent_form():
    if request.method == 'POST':
        old_email = session.get('email')
        updated_email = request.form.get("email")  # Get the new email from the form
        updated_data = {
            "name": request.form.get("name"),
            "email": updated_email,
            "phone": request.form.get("phone"),
            "password": request.form.get("password")
        }
        
        # Update the parent's data
        db.parents.update_one({"email": old_email}, {"$set": updated_data})
        
        # Update the parent_email in the students collection
        db.students.update_many({"parent_email": old_email}, {"$set": {"parent_email": updated_email}})
        
        # Update the email in the session
        session['email'] = updated_email

        return render_template("parent/indexParent.html", user=updated_data)
    
    else:
        email = session.get('email')
        user_data = db.parents.find_one({"email": email})
        if user_data:
            return render_template("parent/ParentProfile.html", user=user_data)
        else:
            return "User not found"




# @parent_bp.route('/profile', methods=['GET', 'POST'])
# def profile_parent_form():
#     if request.method == 'POST':
#         email = session.get('email')
#         updated_data = {
#             "name": request.form.get("name"),
#             "email": request.form.get("email"),
#             "phone": request.form.get("phone"),
#             "password": request.form.get("password")
#         }
#         db.parents.update_one({"email": email}, {"$set": updated_data})
#         return render_template("parent/indexParent.html", user=updated_data)
#     else:
#         email = session.get('email')
#         user_data = db.parents.find_one({"email": email})
#         if user_data:
#             return render_template("parent/ParentProfile.html", user=user_data)
#         else:
#             return "User not found"

@parent_bp.route("/MyStudent", methods=['GET'])
def MyStudent_form():
    # session['origin'] = 'MyStudentList'
    email = session.get('email')
    parent = db.parents.find_one({"email": email})
    if parent:
        students1 = []
        for student_email in parent.get('students', []):
            student = db.students.find_one({"email": student_email})
            if student:
                students1.append(student)

        return render_template("parent/MyStudentList.html", students=students1)
    else:
        return "Parent not found"
    

@parent_bp.route("/editstudentquestionnaire", methods=['GET'])
def edit_student_questionnaire():
    email = request.args.get('email')
    parent_email = request.args.get('parent_email')
    
    # Use the email to fetch the questionnaire data
    questionnaire_data = db.questionnaire.find_one({"student_email": email})
    
    if questionnaire_data:
        return render_template('parent/EditStudentQuestionnaire.html', questionnaire=questionnaire_data)
    else:
        return "Questionnaire not found"


@parent_bp.route("/updatestudentquestionnaire", methods=['POST'])
def update_studentb_questionnaire():
    form_data = request.form.to_dict()
    email = form_data.get('email')  # Use the hidden field from the form

    questionnaire_data = {
        "student_email": form_data.get('email'),
        "parent_email": form_data.get('parent_email'),
        "full_name": form_data.get('fullName'),
        "grade": form_data.get('grade'),
        "rating": form_data.get('rating'),
        "first_subject": form_data.get('firstSubject'),
        "second_subject": form_data.get('secondSubject'),
    }

    db.questionnaire.update_one({"student_email": email}, {"$set": questionnaire_data})
    return render_template('parent/indexParent.html')

@parent_bp.route("/Tips", methods=['GET'])
def Tips_page():
    return render_template("parent/Tips.html")


@parent_bp.route("/payment/<lesson_id>", methods=['GET'])
def payment_page(lesson_id):
    parent_email = session.get('email')
    if not parent_email:
        return redirect(url_for('login'))

    lesson = db.private_lesson.find_one({'_id': ObjectId(lesson_id), 'parent_email': parent_email})
    if not lesson:
        return redirect(url_for('parent_bp.lessons_payments_page'))

    return render_template("parent/payment.html", lesson=lesson)

@parent_bp.route('/lessons_payments')
def lessons_payments_page():
    parent_email = session.get('email')
    if not parent_email:
        return redirect(url_for('login'))

    lessons = db.private_lesson.find({'parent_email': parent_email})
    lessons_list = []
    for lesson in lessons:
        if lesson.get('date') and lesson.get('paid') == False:
            student = db.students.find_one({'email': lesson['student_email']})
            lesson['student_name'] = student['name'] if student else lesson['student_email']
            lessons_list.append(lesson)

    return render_template('parent/lessons_payments.html', lessons=lessons_list)

@parent_bp.route("/process_payment/<lesson_id>", methods=['POST'])
def process_payment(lesson_id):
    parent_email = session.get('email')
    if not parent_email:
        return redirect(url_for('login'))

    lesson = db.private_lesson.find_one({'_id': ObjectId(lesson_id), 'parent_email': parent_email})
    if not lesson:
        return redirect(url_for('parent_bp.lessons_payments_page'))

    db.private_lesson.update_one({'_id': ObjectId(lesson_id)}, {'$set': {'paid': True}})
    return redirect(url_for('parent_bp.Parent_Index'))




@parent_bp.route('/select_child_uploadQ', methods=['GET'])
def select_child_uploadQ():
    parent_email = session.get('email')
    parent = db.parents.find_one({'email': parent_email})
    children = parent.get('students', [])
    return render_template('parent/select_child_uploadQ.html', children=children)


@parent_bp.route("/uplod_question", methods=['GET'])
def upload_question():
    child_email = request.args.get('child_email')
    session['child_email'] = child_email  

    if not child_email:
        return redirect(url_for('parent_bp.select_child'))
    return render_template('parent/upload_question.html', child_email=child_email)
   

@parent_bp.route('/save_question', methods=['POST'])
def save_question():
    question = request.form.get('question')
    possible_answers = request.form.getlist('possible_answers[]')
    correct_answer = request.form.get('correct_answer')
    explanation = request.form.get('explanation')
    child_email = session.get('child_email')
    
    # Save to the database
    db.parentQuestion.insert_one({
        'child_email': child_email,
        'question': question,
        'possible_answers': possible_answers,
        'correct_answer': correct_answer,
        'explanation': explanation
    })

    action = request.form.get('action')
    
    if action == 'insert_another':
        return render_template('parent/upload_question.html', child_email=child_email)
    else:
        return redirect(url_for('parent_bp.some_confirmation_page'))



@parent_bp.route('/some_confirmation_page', methods=['GET'])
def some_confirmation_page():
    return render_template('parent/confirmation.html')

@parent_bp.route('/select_child', methods=['GET'])
def select_child():
    parent_email = session.get('email')
    parent = db.parents.find_one({'email': parent_email})
    children = parent.get('students', [])
    return render_template('parent/select_child.html', children=children)


@parent_bp.route("/progress", methods=['GET'])
def progress():
    student_email = request.args.get('student_email')
    return render_template('parent/progress.html', student_email=student_email)


@parent_bp.route('/show_progress', methods=['GET'])
def show_progress():
    child_email = request.args.get('child_email')
    if not child_email:
        return redirect(url_for('parent_bp.select_child'))

    # Fetch child's progress from both collections
    child_procss_data = db.childProcess.find_one({'student_email': child_email})
    tests_eval_data = db.testsEval.find_one({'student_email': child_email})

    if not child_procss_data and not tests_eval_data:
            return render_template('parent/progress.html', progress_data={}, child_email=child_email)

        
    if not child_procss_data:
        progress_data = {
            'tests_eval': tests_eval_data.get('answers', [])
        }

    elif not tests_eval_data:
        progress_data = {
            'child_procss': child_procss_data.get('answers', []),
    }
          
    else:
        # Combine and process data as needed for display
        progress_data = {
            'child_procss': child_procss_data.get('answers', []),
            'tests_eval': tests_eval_data.get('answers', [])
        }

    return render_template('parent/progress.html', progress_data=progress_data, child_email=child_email)

@parent_bp.route('/view_reports', methods=['GET'])
def view_reports():
    print("View reports route accessed.")  # Debugging line
    parent_email = session.get('email')
    if not parent_email:
        print("No email found in session.")  # Debugging line
        return render_template('parent/reports.html', error="No email found in session.")

    # Fetch the list of student emails from the parent table
    parent_record = db.parents.find_one({'email': parent_email})
    if not parent_record:

app/modules/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
import pymongo
from modules.users.student.models import Student
from modules.users.teacher.models import Teacher
from modules.users.parent.models import Parent
import modules.users.utils as utils

# Create a blueprint named 'users_bp'
users_bp_main = Blueprint('users_bp_main', __name__)

client = pymongo.MongoClient("mongodb+srv://Osnat:123456!@cluster1.7pvmkvu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1")
db = client.get_database("total_records")


@users_bp_main.route("/home", methods=['GET'])
def Home():
    return render_template("index.html")

@users_bp_main.route("/signup", methods=['GET'])
def signup_form():
    return render_template("signupPage.html")


# @users_bp_main.route('/student_questionnaire', methods=['GET', 'POST'])
# def view_student_questionnaire():
#     email = request.args.get('email')
#     origin = session.get('origin') 
#     student = db.students.find_one({"email": email})

#     if origin == 'MyStudentList':
#         email = request.args.get('email')
#         if request.method == 'POST':
#             updated_questionnaire_data = {
#                 "student_email": request.form.get('email'),
#                 "parent_email": request.form.get('parent_email'),
#                 "full_name": request.form.get('fullName'),
#                 "grade": request.form.get('grade'),
#                 "rating": request.form.get('rating'),
#                 "first_subject": request.form.get('firstSubject'),
#                 "second_subject": request.form.get('secondSubject'),
#             }
#             db.questionnaire.update_one({"email": email}, {"$set": updated_questionnaire_data})
#             return redirect(url_for('parent/indexParent'))
#         else:
#             email = request.args.get('email')
#             questionnaire_data = db.questionnaire.find_one({"email": email})
#             if questionnaire_data:
#                 return render_template("student/questionnaire.html", student=questionnaire_data)
#     elif origin == 'signuppage':
#         return redirect(url_for('student.bp.questionnaire'))
#     else:
#         return "User not found"

#     return render_template('student/questionnaire.html', student=student)

@users_bp_main.route("/signup", methods=['POST'])
def signup():
    data = request.form.to_dict()
    email = data.get('email')

    if not utils.verify_name(data.get('name')):
        return render_template("signupPage.html", error="Name must contain only English letters.", form_data=data)

    # Validate phone number
    if not utils.verify_phone_number(data.get('phone')):
        return render_template("signupPage.html", error="Phone number must consist of exactly 10 digits.", form_data=data)

    # Validate password
    if not utils.verify_password(data.get('password')):
        return render_template("signupPage.html", error="Password must be at least 6 characters long and contain at least one letter and one digit.", form_data=data)

    if db.parents.find_one({"email": email}) or db.teachers.find_one({"email": email}) or db.students.find_one({"email": email}):
        return render_template("signupPage.html", error="Email already exists. Please use a different email.", form_data=data)

    if data.get('role') == 'Student':
        parent_email = data.get('parent_email')
        parent = db.parents.find_one({"email": parent_email, "role": "Parent"})
        if not parent:
            return render_template("signupPage.html", error="Parent email not found. Please provide a valid parent email.", form_data=data)

        db.parents.update_one({"email": parent_email}, {"$addToSet": {"students": data['email']}})
        data["parent_email"] = parent_email
        
        user = Student().signup(data)
        db.students.insert_one(user)
        session['origin'] = 'signuppage'
        return redirect(url_for('student_bp.questionnaire', email=data['email']))
    
    elif data.get('role') == 'Parent':
        user = Parent().signup(data)
        db.parents.insert_one(user)
    
    else:
        grade_range = data.get('grade_range')
        teacher_age = data.get('teacher_age')
        user = Teacher().signup(data)
        user["grade_range"] = grade_range
        user["teacher_age"] = teacher_age
        db.teachers.insert_one(user)
    
    return redirect(url_for('home'))


@users_bp_main.route("/login", methods=['GET'])
def login_form():
    return render_template("login.html")

@users_bp_main.route("/login", methods=['POST'])
def login():
    data = request.form
    email = data.get('email')
    password = data.get('password')

    parent = db.parents.find_one({"email": email, "password": password})
    if parent:
        session['email'] = email
        session['name'] = parent.get('name')  # Assuming 'name' is a field in the parents collection
        return render_template('parent/indexParent.html')

    teacher = db.teachers.find_one({"email": email, "password": password})
    if teacher:
        session['email'] = email
        session['name'] = teacher.get('name')  # Assuming 'name' is a field in the teachers collection
        return render_template('teacher/indexTeacher.html')

    student = db.students.find_one({"email": email, "password": password})
    if student:
        session['email'] = email
        session['name'] = student.get('name')  # Assuming 'name' is a field in the students collection
        return render_template('student/indexStudent.html')

    # If login fails, pass back the email and an error message
    return render_template("login.html", error="Invalid username or password.", email=email)

@users_bp_main.route("/FQA", methods=['GET'])
def FQA_page():
    return render_template("FQA.html")

app/templates/FQA.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>FAQ - MathTake</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Include your stylesheets and libraries -->
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>
<body>
    <div class="container-xxl bg-white p-0">
        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0">
            <a href="index.html" class="navbar-brand">
                <h1 class="m-0 text-primary"><i class="fa fa-book-reader me-3"></i>MathTake</h1>
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav mx-auto">
                    <a href="{{ url_for('users_bp_main.Home') }}" class="nav-item nav-link">Home</a>
                    <a href="{{ url_for('users_bp_main.FQA_page') }}" class="nav-item nav-link active">FAQ</a> <!-- Added FAQ link -->
                </div>
                <a href="{{ url_for('users_bp_main.signup_form') }}" class="btn btn-primary rounded-pill px-3 d-none d-lg-block">Sign Up<i class="fa fa-arrow-right ms-3"></i></a>
                <a href="{{ url_for('users_bp_main.login_form') }}" class="btn btn-primary rounded-pill px-3 d-none d-lg-block">Log In<i class="fa fa-arrow-right ms-3"></i></a>
            </div>
        </nav>
        <!-- Navbar End -->

        <!-- FAQ Section Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center mx-auto mb-5" style="max-width: 600px;">
                    <h1 class="mb-3">Frequently Asked Questions</h1>
                    <p>Your questions answered here. If you don't find what you're looking for, feel free to contact us.</p>
                </div>
                <div class="accordion" id="faqAccordion">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                What is MathTake?
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#faqAccordion">
                            <div class="accordion-body">
                                MathTake is an online platform that makes learning math fun and interactive for children.
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                How do I schedule a private lesson?
                            </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#faqAccordion">
                            <div class="accordion-body">
                                You can schedule a private lesson by logging into your account, navigating to the 'Schedule Lesson' section, and selecting a suitable date and time with your preferred teacher.
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                How can I sign up for MathTake?
                            </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#faqAccordion">
                            <div class="accordion-body">
                                You can sign up for MathTake by clicking the 'Sign Up' button in the navigation bar and filling out the registration form.
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                How can I make a payment for a lesson?
                            </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#faqAccordion">
                            <div class="accordion-body">
                                Payments can be made through the 'Payments' section of the website. Enter your payment details and follow the on-screen instructions to complete the transaction.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- FAQ Section End -->

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-light mb-4">Quick Links</h5>
                        <a href="{{ url_for('users_bp_main.Home') }}" class="nav-item nav-link">Home</a>
                        <a href="#about" class="nav-item nav-link">About Us</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-light mb-4">Contact Us</h5>
                        <p><i class="fa fa-map-marker-alt me-3"></i>Sami Shaamon, Beer Sheva, Israel</p>
                        <p><i class="fa fa-phone-alt me-3"></i>+972 845 6789</p>
                        <p><i class="fa fa-envelope me-3"></i>MathTake@gmail.com</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
    </div>

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary btn-lg-square rounded-0 back-to-top"><i class="bi bi-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js')}}"></script>
</script>

<!-- Template Javascript -->
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>MathTake</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap"
        rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <link href="{{ url_for('static', filename='lib/animate/animate.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">

    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <div class="container-xxl py-5">
            <div class="container">
                <div class="bg-light rounded">
                    <div class="row g-0">
                        <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                            <div class="h-100 d-flex flex-column justify-content-center p-5">
                                <h1 class="mb-4">Login</h1>
                                {% if error %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                </div>
                                {% endif %}
                                <form id="login-form" class="form" action="{{ url_for('users_bp_main.login') }}"
                                    method="post">
                                    <div class="row g-3">

                                        <div class="col-sm-12">
                                            <div class="form-floating">
                                                <input type="text" name="email" id="email" class="form-control border-0"
                                                    placeholder="Email" required value="{{ email if email else '' }}">
                                                <label for="email">Email</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-12">
                                            <div class="form-floating">
                                                <input type="password" name="password" id="password"
                                                    class="form-control border-0" placeholder="Password" required>
                                                <label for="password">Password</label>
                                            </div>
                                        </div>

                                        <div class="col-12">
                                            <button class="btn btn-primary w-100 py-3" type="submit">Submit</button>
                                        </div>
                                        <div class="col-12 text-center mt-3">
                                            <p>Don't have an account? <a
                                                    href="{{ url_for('users_bp_main.signup_form') }}">Register here</a>
                                            </p>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s" style="min-height: 400px;">
                            <div class="position-relative h-100">
                                <img class="position-absolute w-100 h-100 rounded"
                                    src="{{ url_for('static', filename='img/about-1.jpg') }}"
                                    style="object-fit: cover;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/easing/easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/waypoints/waypoints.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/owlcarousel/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>